### ISSUE TITLE
audioswitcher executable fails when started

### ISSUE THREAD

**Issue by dtgm** [dtgm/chocolatey-packages#141]
```powershell
PS C:\> audioswitcher

Unhandled Exception: System.ComponentModel.Win32Exception: The specified executable is not a valid application for this
OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at shim.CommandExecutor.execute(String process, String arguments, String working_directory, Boolean is_gui, Boolean w
ait_for_exit, Boolean requires_elevation)
   at shim.ShimProgram.Main(String[] args)
```

**Comment by dtgm** [comment]
### also, failing to build properly

* 1.6.9.102
* 1.6.7.96
* 1.6.8.99

have all failed to build and get pushed to chocolatey.
